#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
#![allow(improper_ctypes_definitions)]
#![allow(clippy::upper_case_acronyms)]

/* automatically generated by rust-bindgen 0.72.0 */

unsafe extern "C" {
    pub fn ten_get_runtime_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn ten_get_global_log_path() -> *const ::std::os::raw::c_char;
}
